version: 2

sources:
  - name: desafio_lh_marcelo
    description: "Tabelas Raw do Adventure Works"
    tables:
      - name: address

      - name: countryregion

      - name: creditcard

      - name: customer

      - name: person

      - name: product

      - name: salesorderdetail

      - name: salesorderheader

      - name: salesorderheadersalesreason

      - name: salesreason

      - name: salesterritory

      - name: stateprovince
